name: Publish Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  decide-what-to-push:
    name: Only push changed images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            python:
              - modified: 'python/3.9-venv-ubuntu/Dockerfile'
            ubuntu:
              - modified: 'ubuntu/20.04/Dockerfile'
      - name: publish ubuntu image
        if: steps.filter.ubuntu == 'true'
        uses: ./.github/actions/push-docker-image
        with:
          build-context: ubuntu/20.04
          image-name: cesarila/ubuntu
      - name: publish python image
        if: steps.filter.python == 'true'
        uses: ./.github/actions/push-docker-image
        with:
          build-context: python/3.9-venv-ubuntu
          image-name: cesarila/python
